Repository jbergstroem/mariadb-alpine, pull requests merged in 2021-05, with the labels that each got.

#73 ci: rename dependabot label
  .github/dependabot.yml
Labels: area: ci, type: change

#74 fix: rename dependabot config attribute
  .github/dependabot.yml
Labels: area: ci, type: bug

#76 Fix #72 - Add more Docker images and add port example
  README.md
Labels: area: documentation

#77 ci: fail any hadolint output
  .github/workflows/lint.yml
Labels: area: ci, type: change

#75 Improve image size and layers
  Dockerfile
  sh/clean.sh
Labels: area: docker, type: change
